# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-17 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='Motocykl')),
                ('opis', models.TextField(blank=True, help_text='Opis motocyklu')),
                ('typ', models.CharField(choices=[('CHOPPER', 'Chopper'), ('CLASSIC', 'Klasyk'), ('CROSS', 'Cross'), ('CRUISER', 'Cruiser'), ('ENDURO', 'Enduro'), ('NAKED', 'Naked'), ('SKUTER', 'Skuter'), ('SPORT', 'Sportowy'), ('TURIST', 'Turystyczny'), ('CUSTOM', 'Inny')], default='CUSTOM', max_length=1)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField(auto_now_add=True, verbose_name='dodano')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfMoror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='części')),
                ('jarski', models.BooleanField(default=False, help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarian', verbose_name='jarski?')),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='czesci', to='motor.Motor')),
            ],
        ),
    ]
