# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-17 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('motor', '0002_auto_20180117_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motor',
            options={'verbose_name_plural': 'motocykle'},
        ),
        migrations.AlterModelOptions(
            name='partofmotor',
            options={'verbose_name': 'część', 'verbose_name_plural': 'części'},
        ),
        migrations.RenameField(
            model_name='motor',
            old_name='opis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='motor',
            old_name='nazwa',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='partofmotor',
            name='jarski',
        ),
        migrations.RemoveField(
            model_name='partofmotor',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='motor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motor',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dodano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='types',
            field=models.CharField(choices=[('CHOPPER', 'Chopper'), ('CLASSIC', 'Klasyk'), ('CROSS', 'Cross'), ('CRUISER', 'Cruiser'), ('ENDURO', 'Enduro'), ('NAKED', 'Naked'), ('SKUTER', 'Skuter'), ('SPORT', 'Sportowy'), ('TURIST', 'Turystyczny'), ('CUSTOM', 'Inny')], default='CUSTOM', max_length=15),
        ),
        migrations.AddField(
            model_name='partofmotor',
            name='minorPerson',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli motor dla nieletnich', verbose_name='minor'),
        ),
        migrations.AddField(
            model_name='partofmotor',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='część'),
            preserve_default=False,
        ),
    ]
