# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0005_auto_20180117_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addpartofmotor',
            options={'verbose_name': 'dodatek', 'verbose_name_plural': 'Dodadki'},
        ),
        migrations.AddField(
            model_name='addpartofmotor',
            name='delete_part',
            field=models.BooleanField(default=False, verbose_name='Usuń'),
        ),
        migrations.AlterField(
            model_name='addpartofmotor',
            name='broken',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli dodatkowa część jest uszkodzona', verbose_name='Zepsute'),
        ),
        migrations.AlterField(
            model_name='addpartofmotor',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addtionName', to='motor.Motor'),
        ),
        migrations.AlterField(
            model_name='addpartofmotor',
            name='nameOwn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dodatek do motocykla'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data dodania postu'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='types',
            field=models.CharField(choices=[('CHOPPER', 'Chopper'), ('CLASSIC', 'Klasyk'), ('CROSS', 'Cross'), ('CRUISER', 'Cruiser'), ('ENDURO', 'Enduro'), ('NAKED', 'Naked'), ('SKUTER', 'Skuter'), ('SPORT', 'Sportowy'), ('TURIST', 'Turystyczny'), ('CUSTOM', 'Inny')], default='CUSTOM', max_length=15, verbose_name='Typ motocykla'),
        ),
    ]
